# settings.py
MAX_ELEMS_ON_PAGE = 6

# users.models.py
MAX_LEN_EMAIL = 254
MAX_LEN_USERNAME = 150

# recipes.models.py
MAX_LEN_RECIPE_NAME = 200
HEX_LEN = 7
MAX_LEN_MEASUREMENT_UNIT = 40
MIN_COOKING_VALUE = 1
MAX_COOKING_VALUE = 300
MIN_INGREDIENT_AMOUNT = 1
